name: Build and deploy ASP.Net Core app to Azure Web App - TikTokBE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{ github.workspace }}/myapp"

      - name: List files in myapp directory
        run: ls ${{ github.workspace }}/myapp

      - name: Create ZIP package for deployment
        run: |
          cd ${{ github.workspace }}/myapp
          zip -r myapp.zip .  # Tạo gói ZIP từ thư mục myapp
          ls -la  # Kiểm tra các file sau khi zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp/myapp.zip # Chỉ định đường dẫn tới file zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "TikTokBE"
          slot-name: "Production"
          package: ${{ github.workspace }}/myapp/myapp.zip # Chỉ định file ZIP đã tạo

      - name: Apply database migrations
        run: dotnet ef database update
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.MYSQL_CONNECTION_STRING }}
